### PR TITLE
Few improvements

### LINKED ISSUE #139: Loading too many shops makes server crash
Hi,

On my server there is currently ±1600 shops, it takes approximately 30 seconds to load, meaning during these 30 seconds the server is completely halted. But this morning, it took more than 1 minute, so Spigot did stop as the server stopped responding for more than 60 seconds.

A possible workaround would be to lazy-load the hologram text, or improve evaluation performance.
By the time of writing I did a commit in PR #135 to address this issue.

```
[05:04:40] [Spigot Watchdog Thread/ERROR]: The server has stopped responding!
[05:04:40] [Spigot Watchdog Thread/ERROR]: Please report this to http://www.spigotmc.org/
[05:04:40] [Spigot Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[05:04:40] [Spigot Watchdog Thread/ERROR]: Spigot version: git-Spigot-21fe707-e1ebe52 (MC: 1.8.8)
[05:04:40] [Spigot Watchdog Thread/ERROR]: ------------------------------
[05:04:40] [Spigot Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Spigot!):
[05:04:40] [Spigot Watchdog Thread/ERROR]: ------------------------------
[05:04:40] [Spigot Watchdog Thread/ERROR]: Current Thread: Server thread
[05:04:40] [Spigot Watchdog Thread/ERROR]: 	PID: 25 | Suspended: false | Native: false | State: RUNNABLE
[05:04:40] [Spigot Watchdog Thread/ERROR]: 	Stack:
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		java.lang.System.identityHashCode(Native Method)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		java.util.IdentityHashMap.hash(IdentityHashMap.java:294)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		java.util.IdentityHashMap.put(IdentityHashMap.java:425)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.codegen.CompileUnit.addFunctionInitializer(CompileUnit.java:132)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.codegen.CodeGenerator.newFunctionObject(CodeGenerator.java:4529)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.codegen.CodeGenerator.leaveFunctionNode(CodeGenerator.java:2148)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:336)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:55)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:628)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.codegen.CompilationPhase.access$100(CompilationPhase.java:55)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:418)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:624)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:654)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.runtime.Context.compile(Context.java:1319)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1253)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.internal.runtime.Context.compileScript(Context.java:625)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:532)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:521)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		de.epiceric.shopchest.config.HologramFormat.evalRequirement(HologramFormat.java:132)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		de.epiceric.shopchest.config.HologramFormat.getFormat(HologramFormat.java:54)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		de.epiceric.shopchest.shop.Shop.getHologramText(Shop.java:252)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		de.epiceric.shopchest.shop.Shop.createHologram(Shop.java:188)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		de.epiceric.shopchest.shop.Shop.create(Shop.java:116)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		de.epiceric.shopchest.utils.ShopUtils$1$1.onResult(ShopUtils.java:249)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		de.epiceric.shopchest.utils.ShopUtils$1$1.onResult(ShopUtils.java:245)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		de.epiceric.shopchest.utils.Callback$1.run(Callback.java:21)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[05:04:40] [Spigot Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by MineTheCube**
# Few improvements

This PR aims to fix small issues and add code improvements, in order to improve quality and maintainability.

**CHANGES**
- [x] Add `final` attribute to fields, to better see what changes and what doesn't
- [x] Improve update sight shops performance using vectors 
- [x] Avoid creating async tasks in already async thread
- [x] Refactor method/variables order
- [x] Fix for hologram not disappearing when reloading
- [x] Fix ConcurrentModificationException when iterating over `getShops()`
- [x] Fix hologram being shown/hidden incorrectly
- [x] Fix #139, improve loading shops, especially hologram text/format

**TODO**
- [x] Make all changes
- [x] Ensure it compiles
- [x] Test it on local server
- [x] Test it on real server

### CODE REVIEW

**Comment by MineTheCube** [comment]
It should work now, I tested it locally, I'll test on my real server tomorrow.

You can download pre-release 1.12.4 [**here**](https://github.com/MineTheCube/ShopChest/releases/tag/v1.12.4) or build it from [sources](https://github.com/MineTheCube/ShopChest/tree/v1.12.4).

File: src/main/java/de/epiceric/shopchest/shop/ShopItem.java [hunk 1]
```diff
@@ -130,31 +168,38 @@ public void setVisible(final Player p, boolean visible) {
...
     /**
-     * @return {@code net.minecraft.server.[VERSION].EntityItem}
+     * Removes the item. <br>
+     * Item will be hidden from all players
      */
-    public Object getEntityItem() {
-        return entityItem;
+    public void remove() {
+        // Avoid ConcurrentModificationException
+        Deque<Player> queue = new ArrayDeque<>(viewers.size());
```
Comment (EpicEricEE) [inline src/main/java/de/epiceric/shopchest/shop/ShopItem.java]: Couldn't you use this?
```java
new ArrayDeque<>(viewers)
```

File: src/main/java/de/epiceric/shopchest/utils/ShopUtils.java [hunk 2]
```diff
@@ -55,13 +51,27 @@ public boolean isShop(Location location) {
 
     /**
      * Get all shops
+     * Do not use for removing while iteration!
+     *
+     * @see #getShopsCopy()
      * @return Read-only collection of all shops, may contain duplicates
      */
     public Collection<Shop> getShops() {
         return Collections.unmodifiableCollection(new ArrayList<>(shopLocation.values()));
```
Comment (EpicEricEE) [inline src/main/java/de/epiceric/shopchest/utils/ShopUtils.java]: Now both methods return a copy, as in both a new ArrayList is created.

File: src/main/java/de/epiceric/shopchest/utils/ShopUtils.java [hunk 3]
```diff
@@ -278,120 +288,128 @@ public void updateShops(Player player, boolean force) {
...
+
+                    // If not in sight
+                    shop.getHologram().hidePlayer(player);
+                }
+            }
+        }
+
+        for (Shop shop : otherShopsInSight) {
+            // we already checked hasHologram() before adding it
+            shop.getHologram().hidePlayer(player);
```
Comment (EpicEricEE) [inline src/main/java/de/epiceric/shopchest/utils/ShopUtils.java]: The other shops in sight should only be hidden if ``only-show-first-shop-in-sight`` is enabled.

File: src/main/java/de/epiceric/shopchest/utils/ShopUtils.java [hunk 4]
```diff
@@ -278,120 +288,128 @@ public void updateShops(Player player, boolean force) {
...
-    /**
-     * Update hologram and item of the shop for a player based on their distance to each other
-     * @param shop Shop to update
-     * @param player Player to show the update
-     */
-    public void updateShop(Shop shop, Player player) {
-        double holoDistSqr = Math.pow(plugin.getShopChestConfig().maximal_distance, 2);
-        double itemDistSqr = Math.pow(plugin.getShopChestConfig().maximal_item_distance, 2);
+                        double angle = targetLocation.toVector().subtract(pVec).angle(pDir);
+                        double distance = Math.sqrt(distanceSquared);
```
Comment (EpicEricEE) [inline src/main/java/de/epiceric/shopchest/utils/ShopUtils.java]: I always tried to avoid using square roots, since it is said that it is uses a lot of computing power. I'm also not sure, how this method to get the shops in sight is better than the old one, except some minor changes that could be made.

File: src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java [hunk 5]
```diff
@@ -691,18 +691,8 @@ private void create(final Player executor, final Location location, final ItemSt
...
-                }
-            }
-            if (p.getLocation().distanceSquared(location) <= Math.pow(config.maximal_item_distance, 2)) {
-                if (shop.getItem() != null) {
-                    shop.getItem().setVisible(p, true);
-                }
-            }
-        }
+        // next update will display the new shop
+        plugin.getShopUtils().resetPlayerLocation(executor);
```
Comment (EpicEricEE) [inline src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java]: If there is someone standing next to the executor while creating the shop, it will not be shown to him, but only for the executor.

File: pom.xml [hunk 6]
```diff
@@ -25,7 +25,7 @@
         <maven.compiler.target>${jdkVersion}</maven.compiler.target>
 
         <!-- Versioning -->
-        <version.number>1.12.3</version.number>
+        <version.number>1.12.4</version.number>
```
Comment (EpicEricEE) [inline pom.xml]: Not yet

File: src/main/java/de/epiceric/shopchest/shop/ShopItem.java (hunk 1 above)
Comment (MineTheCube) [inline src/main/java/de/epiceric/shopchest/shop/ShopItem.java]: Yep, I'll change that part of code.

File: src/main/java/de/epiceric/shopchest/utils/ShopUtils.java (hunk 2 above)
Comment (MineTheCube) [inline src/main/java/de/epiceric/shopchest/utils/ShopUtils.java]: Oops, I'll fix

File: src/main/java/de/epiceric/shopchest/utils/ShopUtils.java (hunk 3 above)
Comment (MineTheCube) [inline src/main/java/de/epiceric/shopchest/utils/ShopUtils.java]: Shops are added to collection only if `firstShopInSight` is true.
Check line [352](https://github.com/EpicEricEE/ShopChest/pull/135/files#diff-ba3fde9183b4e821a47b295dcc79961eR352) of `ShopUtils.java` ;)

File: src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java (hunk 5 above)
Comment (MineTheCube) [inline src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java]: Will iterate over world#getPlayers()

File: pom.xml (hunk 6 above)
Comment (MineTheCube) [inline pom.xml]: Well, since current update 1.12.3, you'll have to bump version, right?

But I can revert it to 1.12.3 if you want to.

Comment (EpicEricEE) [inline pom.xml]: Leave it, it's alright. I normally bump the version only when I know that I won't commit something anymore.

File: src/main/java/de/epiceric/shopchest/utils/ShopUtils.java (hunk 3 above)
Comment (EpicEricEE) [inline src/main/java/de/epiceric/shopchest/utils/ShopUtils.java]: Ok, it's a bit confusing though.

File: src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java (hunk 5 above)
Comment (EpicEricEE) [inline src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java]: Then every time someone in the same world as you creates a shop, the items for every shop will be respawned, which might look odd for someone looking on a shop. It would be better if only the newly created shop will be updated.

File: src/main/java/de/epiceric/shopchest/utils/ShopUtils.java (hunk 4 above)
Comment (MineTheCube) [inline src/main/java/de/epiceric/shopchest/utils/ShopUtils.java]: Square root isn't that expensive, I tested and optimised (you'll see in new commit) and got these results (after ±15 minutes of update at `FASTEST` rate):

```
[20:22:12 INFO]: vectorMethod took in average 3207.4862432501927ns
[20:22:12 INFO]: locationMethod took in average 7770.374328472755ns
```

So it's roughly 2x faster.

File: src/main/java/de/epiceric/shopchest/utils/ShopUtils.java (hunk 3 above)
Comment (MineTheCube) [inline src/main/java/de/epiceric/shopchest/utils/ShopUtils.java]: You're right, what about:
```java
        if (firstShopInSight) {
            // we hide other shop as we wan't to display only the first
            for (Shop shop : otherShopsInSight) {
                // we already checked hasHologram() before adding it
                shop.getHologram().hidePlayer(player);
            }
        }
```

File: src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java (hunk 5 above)
Comment (MineTheCube) [inline src/main/java/de/epiceric/shopchest/listeners/ShopInteractListener.java]: Items won't be respawned, as it will check against `viewers.contains(UUID)` and so on. So it will simply update if needed, just like if player has moved.

**Comment by dan-nkl** [comment]
When to expect 1.12.4?

**Comment by MineTheCube** [comment]
The last commit improves drastically performance for conditions with only one operator, such as:
```java
true // in case of: ADMIN_SHOP
100.0 >= 50.0 // in case of: BUY_PRICE > 50
"STONE" == "DIAMOND_SWORD" // in case of: ITEM_TYPE == "DIAMOND_SWORD"
```
It doesn't handle complex comparison such as `(...) && (...)`, but I do think that simple conditions are used the most.

For the benchmark:
```
INPUT: 100.0 >= 50.0
RESULT SIMPLE: true, in 3 ms
RESULT JAVASCRIPT: true, in 452 ms
```

Also, it adds almost zero overhead, as it performs the regex only if first char matches, and performs the comparison only if regex matches.

**Comment by EpicEricEE** [comment]
Can I merge this?

**Comment by MineTheCube** [comment]
Yes :)

File: pom.xml (hunk 6 above)
Comment (dan-nkl) [inline pom.xml]: "I normally bump the version only when I know that I won't commit something anymore."

Really strange to do it like this ^^
Normally you create a branch with the new version on which you are working the whole time, while the master stays on the last stable... or not?

Comment (EpicEricEE) [inline pom.xml]: Probably that's how you should do it.
